import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import childrenRouter from "./children";
import casesRouter from "./cases";
import healthAssessmentsRouter from "./health-assessments";
import counselingSessionsRouter from "./counseling-sessions";
import guardiansRouter from "./guardians";
import guardianVisitsRouter from "./guardian-visits";
import courtCasesRouter from "./court-cases";
import policeAcquisitionsRouter from "./police-acquisitions";
import educationPlansRouter from "./education-plans";
import releaseRecordsRouter from "./release-records";
import followUpsRouter from "./follow-ups";
import admissionsRouter from "./admissions";
import familySocioeconomicRecordsRouter from "./family-socioeconomic-records";
import riskAssessmentsRouter from "./risk-assessments";
import measurementSurveysRouter from "./measurement-surveys";
import caseRiskAssessmentsRouter from "./case-risk-assessments";
import caseDetailAssessmentsRouter from "./case-detail-assessments";
import caseInterventionPlansRouter from "./case-intervention-plans";
import caseAgreementsRouter from "./case-agreements";
import authRouter from "./auth";
import usersRouter from "./users";
import centersRouter from "./centers";
import adminUnitsRouter from "./admin-units";
import rolesRouter from "./roles";
import workflowRouter from "./workflow";
import reportsRouter from "./reports";
import caseTypesRouter from "./case-types";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/centers", centersRouter);
router.use("/admin-units", adminUnitsRouter);
router.use("/roles", rolesRouter);
router.use("/workflow", workflowRouter);
router.use("/dashboard", dashboardRouter);
router.use("/children", childrenRouter);
router.use("/cases", casesRouter);
router.use("/health-assessments", healthAssessmentsRouter);
router.use("/counseling-sessions", counselingSessionsRouter);
router.use("/guardians", guardiansRouter);
router.use("/guardian-visits", guardianVisitsRouter);
router.use("/court-cases", courtCasesRouter);
router.use("/police-acquisitions", policeAcquisitionsRouter);
router.use("/education-plans", educationPlansRouter);
router.use("/release-records", releaseRecordsRouter);
router.use("/follow-ups", followUpsRouter);
router.use("/admissions", admissionsRouter);
router.use("/family-socioeconomic-records", familySocioeconomicRecordsRouter);
router.use("/risk-assessments", riskAssessmentsRouter);
router.use("/measurement-surveys", measurementSurveysRouter);
router.use("/case-risk-assessments", caseRiskAssessmentsRouter);
router.use("/case-detail-assessments", caseDetailAssessmentsRouter);
router.use("/case-intervention-plans", caseInterventionPlansRouter);
router.use("/case-agreements", caseAgreementsRouter);
router.use("/reports", reportsRouter);
router.use("/case-types", caseTypesRouter);

export default router;
