import { Router, type IRouter } from "express";
import { moduleGuard } from "../middlewares/auth";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import childrenRouter from "./children";
import casesRouter from "./cases";
import healthAssessmentsRouter from "./health-assessments";
import counselingSessionsRouter from "./counseling-sessions";
import guardiansRouter from "./guardians";
import guardianVisitsRouter from "./guardian-visits";
import courtCasesRouter from "./court-cases";
import policeAcquisitionsRouter from "./police-acquisitions";
import educationPlansRouter from "./education-plans";
import releaseRecordsRouter from "./release-records";
import followUpsRouter from "./follow-ups";
import admissionsRouter from "./admissions";
import familySocioeconomicRecordsRouter from "./family-socioeconomic-records";
import riskAssessmentsRouter from "./risk-assessments";
import measurementSurveysRouter from "./measurement-surveys";
import caseRiskAssessmentsRouter from "./case-risk-assessments";
import caseDetailAssessmentsRouter from "./case-detail-assessments";
import caseInterventionPlansRouter from "./case-intervention-plans";
import caseAgreementsRouter from "./case-agreements";
import authRouter from "./auth";
import usersRouter from "./users";
import centersRouter from "./centers";
import adminUnitsRouter from "./admin-units";
import rolesRouter from "./roles";
import workflowRouter from "./workflow";
import reportsRouter from "./reports";
import caseTypesRouter from "./case-types";
import familyTypesRouter from "./family-types";
import classesRouter from "./classes";
import trainingsRouter from "./trainings";
import permissionsRouter from "./permissions";

const router: IRouter = Router();

// ─── Public / infrastructure ─────────────────────────────────────────────────
router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/roles", rolesRouter);
router.use("/centers", centersRouter);
router.use("/admin-units", adminUnitsRouter);
router.use("/users", usersRouter);
router.use("/case-types", caseTypesRouter);
router.use("/family-types", familyTypesRouter);
router.use("/classes", classesRouter);
router.use("/trainings", trainingsRouter);
router.use("/permissions", permissionsRouter);
router.use("/workflow", workflowRouter);

// ─── Module routes — protected by DB-driven permission guard ──────────────────
router.use("/dashboard",                  moduleGuard("dashboard"),           dashboardRouter);
router.use("/admissions",                 moduleGuard("admissions"),          admissionsRouter);
router.use("/children",                   moduleGuard("children"),            childrenRouter);
router.use("/cases",                      moduleGuard("cases"),               casesRouter);
router.use("/family-socioeconomic-records", moduleGuard("family-socioeconomic"), familySocioeconomicRecordsRouter);
router.use("/health-assessments",         moduleGuard("health"),              healthAssessmentsRouter);
router.use("/counseling-sessions",        moduleGuard("counseling"),          counselingSessionsRouter);
router.use("/education-plans",            moduleGuard("education-skills"),    educationPlansRouter);
router.use("/guardians",                  moduleGuard("guardians"),           guardiansRouter);
router.use("/guardian-visits",            moduleGuard("guardians"),           guardianVisitsRouter);
router.use("/court-cases",               moduleGuard("court-cases"),         courtCasesRouter);
router.use("/police-acquisitions",        moduleGuard("police-requisitions"), policeAcquisitionsRouter);
router.use("/risk-assessments",           moduleGuard("risk-assessments"),    riskAssessmentsRouter);
router.use("/release-records",            moduleGuard("release-records"),     releaseRecordsRouter);
router.use("/follow-ups",                moduleGuard("follow-ups"),          followUpsRouter);
router.use("/measurement-surveys",        moduleGuard("health"),              measurementSurveysRouter);
router.use("/case-risk-assessments",      moduleGuard("cases"),               caseRiskAssessmentsRouter);
router.use("/case-detail-assessments",    moduleGuard("cases"),               caseDetailAssessmentsRouter);
router.use("/case-intervention-plans",    moduleGuard("cases"),               caseInterventionPlansRouter);
router.use("/case-agreements",            moduleGuard("cases"),               caseAgreementsRouter);
router.use("/reports",                    moduleGuard("reports"),             reportsRouter);

export default router;
