import { pgTable, text, serial, timestamp, integer, date, boolean } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { childrenTable } from "./children";

export const casesTable = pgTable("cases", {
  id: serial("id").primaryKey(),
  caseId: text("case_id").notNull().unique(),
  childId: integer("child_id").notNull().references(() => childrenTable.id),
  caseOpeningDate: date("case_opening_date"),
  assignedCaseWorker: text("assigned_case_worker"),
  riskLevel: text("risk_level"),
  caseStatus: text("case_status").notNull().default("Open"),
  caseType: text("case_type"),
  caseSummary: text("case_summary"),
  investigationNotes: text("investigation_notes"),
  recommendation: text("recommendation"),
  centerId: integer("center_id"),
  isSpecialCase: boolean("is_special_case").notNull().default(false),
  isPriorityCase: boolean("is_priority_case").notNull().default(false),
  workflowState: text("workflow_state").notNull().default("Draft"),
  workflowNotes: text("workflow_notes"),
  sentBackNotes: text("sent_back_notes"),
  submittedById: integer("submitted_by_id"),
  reviewedByDfId: integer("reviewed_by_df_id"),
  reviewedByCaseworkerId: integer("reviewed_by_caseworker_id"),
  reviewedByProbationId: integer("reviewed_by_probation_id"),
  approvedById: integer("approved_by_id"),

  registrationNumber: text("registration_number"),
  nameEnglish: text("name_english"),
  motherName: text("mother_name"),
  fatherName: text("father_name"),
  guardianName: text("guardian_name"),
  guardianRelationship: text("guardian_relationship"),
  birthRegNo: text("birth_reg_no"),
  disabilityId: text("disability_id"),
  nationality: text("nationality"),
  ethnicity: text("ethnicity"),
  birthplace: text("birthplace"),
  religion: text("religion"),
  occupation: text("occupation"),
  income: text("income"),
  currentAddressDivision: text("current_address_division"),
  currentAddressDistrict: text("current_address_district"),
  currentAddressUpazila: text("current_address_upazila"),
  currentAddressUnion: text("current_address_union"),
  currentAddressVillage: text("current_address_village"),
  permanentAddressDivision: text("permanent_address_division"),
  permanentAddressDistrict: text("permanent_address_district"),
  permanentAddressUpazila: text("permanent_address_upazila"),
  permanentAddressUnion: text("permanent_address_union"),
  permanentAddressVillage: text("permanent_address_village"),
  guardianPhone: text("guardian_phone"),
  email: text("email"),
  livingWith: text("living_with"),
  childProblems: text("child_problems"),
  otherProblems: text("other_problems"),
  referralReason: text("referral_reason"),
  referralContactName: text("referral_contact_name"),
  referralContactAddress: text("referral_contact_address"),
  referralContactPhone: text("referral_contact_phone"),
  referralRelationship: text("referral_relationship"),
  urgentServiceNeeded: boolean("urgent_service_needed"),
  urgentServiceTypes: text("urgent_service_types"),
  referralDestination: text("referral_destination"),
  receiverName: text("receiver_name"),
  receiverIdNo: text("receiver_id_no"),
  intakeDate: date("intake_date"),
  intakeOfficerName: text("intake_officer_name"),
  intakeOfficerDesignation: text("intake_officer_designation"),
  assessorName: text("assessor_name"),
  supervisorName: text("supervisor_name"),

  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const insertCaseSchema = createInsertSchema(casesTable).omit({ id: true, caseId: true, createdAt: true, updatedAt: true });
export type InsertCase = z.infer<typeof insertCaseSchema>;
export type CaseFile = typeof casesTable.$inferSelect;
